core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path("register", views.registration_view, name='register'),
    path('login', views.login_view, name='login'),
    path('editor', views.editor_view, name='editor')
]

instedit/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('core.urls')),
    path('logout/', views.logout_view, name='logout'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import uuid

'''
Overridden the django's built-in Auth User Model with custom user model,
in which email is required for logging in instead of username.
'''


class AccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    profile_pic = models.ImageField(
        'Profile Picture', upload_to='profile_pics', default='knowme/profile_pics/default.jpg')
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = AccountManager()


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

# users can add projects to their account

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from django.contrib.auth import authenticate


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60)

    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'email',
                  'password1', 'password2')


class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid:
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Credentials')

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import RegistrationForm, LoginForm
from django.contrib.auth.decorators import login_required
from .models import Account


def index(request):
    return render(request, 'core/index.html')

def editor_view(request):
    return render(request, 'core/editor.html')


def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')

            account = authenticate(email=email, password=password)
            login(request, account)
            messages.success(request, 'Registration Successfull')
            return redirect('editor')

        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
        context['registration_form'] = form

    return render(request, 'core/registration.html', context)


'''
registered user can login with his email and password
'''


def login_view(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect('index')
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('editor')

    else:
        form = LoginForm()
    context['login_form'] = form
    return render(request, 'core/login.html', context)


'''
logged in user can logout
'''


@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Successfully logged out', extra_tags='alert')
    return redirect('index')

templates/core/editor.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'editor.css' %}">
    <title>InstEdit</title>
  </head>
  <body>
    <div class="file-upload-section" onclick="selectImage()">
      <input id='foto-file' type='file'>
      Select Image
    </div>
    <div class="upper-buttons-section">
      <table class="buttons-table">
        <tr>
          <td><button class="operation-btn" onclick="crop()">Crop</button> </td>
          <td><button class="operation-btn" onclick="flipVertically()">Flip</button> </td>
          <td><button class="operation-btn" onclick="displayRange()">Rotate <input type="range" id="display-range" min='0' max='300' onchange="rotate(this)" value="0"> </button> </td>
        </tr>
      </table>
    </div>
    <div class="img-container">
      <img id='foto-image' class='image'/>
    </div>
    <div class="buttons-section">
      <table class="buttons-table">
        <tr>
          <td><button class="operation-btn" onclick="makeGrayScale()">Grayscale</button></td>
          <td><button class="operation-btn" onclick="makeBright()">Brighter</button></td>
          <td><button class="operation-btn" onclick="makeDark()">Darker</button></td>
        </tr>
        <tr>
          <td><button class="operation-btn" onclick="makeBlur()">Blur</button></td>
          <td><button class="operation-btn" onclick="makeEmboss()">Emboss</button></td>
          <td><button class="operation-btn" onclick="makeSharp()">Sharp</button></td>
        </tr>
        <tr>
          <td><input type="color" id='color-picker' value='#000000' oninput="makeColorize(this)">
            <button class="operation-btn" onclick="openColorPicker()">Colorize</button>
          </td>
          <td><input type="color" id='colorize-color-picker' value="#000000" oninput="applyColorFilter(this)">
            <button class="operation-btn" onclick="openColorFilterPicker()">Color Filter</button>
          </td>
          <td><button class="operation-btn" onclick=""="makeTransparent()">
            <div id='color-preview'></div>Transparent</button>
          </td>
        </tr>
        <tr>
          <td colspan="3"><button class='operation-btn download-btn' onclick="download()">Download</button></td>
        </tr>
      </table>
    </div>

    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <script src="https://rawcdn.githack.com/kousik19/foto.js/045defe1a5ce06220e084e4e6f6fbaccb7621841/foto.min.js"></script>
  </body>
</html>

templates/core/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>InstEdit</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'>
    <link rel="stylesheet" href="{% static 'styles.css' %}">

  </head>

  <body>
    <div class="container">
      <div class="card-wrap">
        <div class="card border-0 shadow card--welcome is-show" id="welcome">
          <div class="card-body">
            <h2 class="card-title">WELCOME</h2>
            <div class="btn-wrap">
              <a class="btn btn-lg btn-register js-btn" data-target="register"
                href="{% url 'core:register' %}">REGISTER</a>
              <a class="btn btn-lg btn-login js-btn" data-target="login" href="{% url 'core:login' %}">LOGIN</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </body>

</html>

templates/core/login.html
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>

  <body>
    <div class="container">
      <div class="card-wrap">
        <div class="card border-0 shadow card--welcome is-show" id="welcome">
          <div class="card-body">
            <h2 class="card-title">Login here</h2>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %} {% for field in login_form %}
              <p>
                {{field.label_tag}} {{field}}
              </p>
              {% endfor %}
              {% if login_form.non_field_errors %}
              <p>{{login_form.non_field_errors}}</p>
              {% endif %}
              <input type="submit" class="btn-wrap btn btn-lg btn-register js-btn" type="submit" value="Login" />
            </form>
          </div>
  </body>

</html>

templates/core/registration.html
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>

  <body>
    <div class="container">
      <div class="card-wrap">
        <div class="card border-0 shadow card--welcome is-show" id="welcome">
          <div class="card-body">
            <h2 class="card-title">Register here</h2>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %} {% for field in registration_form %}
              <p>
                {{field.label_tag}} {{field}}
                {% for errors in field.errors %}
              <p>{{errors}}</p>

              {% endfor %}
              </p>

              {% endfor %}
              <input class="btn-wrap btn btn-lg btn-register js-btn" type="submit" value="Register" />
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>

</html>